# Generated by Django 4.2.13 on 2024-05-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='Екатеринбург', max_length=150, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='user',
            name='patronymic',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='user',
            name='profession',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Профессия'),
        ),
        migrations.AddField(
            model_name='user',
            name='self_info',
            field=models.TextField(blank=True, max_length=350, null=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='user',
            name='work_experience',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Стаж'),
        ),
    ]
