# Generated by Django 4.2.13 on 2024-05-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, max_length=300, null=True, verbose_name='Описание')),
                ('make_time', models.CharField(blank=True, max_length=100, verbose_name='Время работы')),
                ('image', models.ImageField(blank=True, null=True, upload_to='vacancies_images', verbose_name='Фото')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Вакансию',
                'verbose_name_plural': 'Вакансии',
                'db_table': 'vacancy',
            },
        ),
    ]
